---
title: "Survival Analysis course by Dr.Anat"
author: "Or gamliel"
date: "1 5 2021"
output: html_document
---

```{r}
#  להוריד חבילות נדרשות ולנסות שוב להריץ , גירסא 23.0
install.packages("SemiCompRisks")
install.packages("kableExtra")
install.packages("broom")
install.packages("survival")
#library(survival)
library(survminer)
library(lubridate)
library(survival)
setwd("C:\\org")
library(survival)
library(randomForestSRC)
library(survivalsvm)
library(Hmisc)


```

## Non parametric approaches

### Kaplan-Meier non-parametric analysis


```{r}
#hours צפייה בנתונים
file_path = file.path(getwd(),"48_ hours_sample")
hours <- read.csv(file = '48_ hours_sample.csv')
View(hours)


```



```{r}
# ניעזר בספריות כדי לייבא מידע ופונקציות נדרשות
library(survival)
library(survminer)


#פונקציה זו יוצרת עקומות הישרדות על בסיס נוסחה. בואו ניצור את עקומת ההישרדות הכוללת עבור כל הקבוצה, נקצה אותה לאובייקט "קפלן" ונראה את השמות של אותו אובייקט 
kaplan <- survfit(Surv(time, status) ~ 1, data = lung)
names(kaplan)
print("summary of kaplan-meier:")
summary(kaplan)

```


```{r}
library(survival)
library(survminer)
plot(survfit(Surv(time, status) ~ 1, data = lung), 
     xlab = "ימים שעברו", 
     ylab = "הסיכויים להישרדות")
```


```{r}
(kaplan$n.risk)
kaplan$n.event

plot(kaplan$time[1:25], kaplan$n.event[1:25]/kaplan$n.risk[1:25],xlab="זמן", ylab="אחוז הסיכון", type = "l")
```

```{r}
ggsurvplot( #  ggsurvplot ע"י Kaplan-Meier plot יצירת
  fit = survfit(Surv(time, status) ~ 1, data = lung), 
  xlab = "ימים שעברו", 
  ylab = "הסיכויים להישרדות")

```

### Kaplan-Meier non-parametric analysis by group


```{r}
# Kaplan-Meier non-parametric analysis by group

summary(kaplan)


```


```{r}
summary(survfit(Surv(time, status) ~ 1, data = lung), times = 365.25)
```        
        
```{r}

survfit(Surv(time, status) ~ 1, data = lung)

```
### 

```{r}
# Nelson-Aalen non-parametric analysis
survdiff(Surv(time, status) ~ sex, data = lung)
```


```{r}
sd <- survdiff(Surv(time, status) ~ sex, data = lung)
1 - pchisq(sd$chisq, length(sd$n) - 1)

```
## 

```{r}

# Cox proportional hazard model - coefficients and hazard rates
coxph(Surv(time, status) ~ sex, data = lung)


```



```{r}
coxph(Surv(time, status) ~ sex, data = lung) %>% 
  gtsummary::tbl_regression(exp = TRUE) 
```

```{r}

ggscatter(lung,
x = "ph.karno",
y = "pat.karno",
color = "sex",
title = "מתאם בין ביצועי סולם קרנופסקי, רופא מול פציינט ",
xlab = "מדד הרופא",
ylab = "מדד הפציינט",
add = "reg.line",
add.params = list(color = "lightblue"),
conf.int = TRUE,
ellipse.type = "confidence",
mean.point = TRUE,
mean.point.size = 5,
cor.coef = TRUE,
cor.coeff.args = list(method = "spearman", label.x.npc = "middle", label.y.npc = "bottom")
)
```

```{r}
#חציון ההישרדות  לפי גיל
library(sm)

sm.options(
  list(
    xlab = "גיל",
    ylab = "זמן שנותר לחיות")
  )

sm.survival(
  x = lung$age,
  y = lung$time,
  status = lung$status,
  h = sd(lung$age) / nrow(lung)^(-1/4)
  )
```




```{r}
#  הקו שקיבלנו חלקלק מדיי, ננסה להפחית בשליש את הפרמטר כדי לקבל  
# h = סטיית תקן של המשתנה הרציף
sm.survival(
  x = lung$age,
  y = lung$time,
  status = lung$status,
  h = (1/4) * sd(lung$age) / nrow(lung)^(-1/3)
  )

```

